=== pmonteroj05/proyecto_granja/datos/tienda.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- elementos-->

<xs:element name="tienda">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="semilla" maxOccurs="unbounded"></xs:element>
            <xs:element ref="herramienta" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="semilla">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="nombre" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="tipo" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="precio" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="tiempoCrec" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="beneficio" minOccurs="1" maxOccurs="1"></xs:element>
        </xs:sequence>
        <xs:attribute ref="sem"></xs:attribute>
    </xs:complexType>
</xs:element>

<xs:element name="nombre" type="xs:string"></xs:element>
<xs:element name="tipo" type="xs:string"></xs:element>
<xs:element name="precio" type="num"></xs:element>
<xs:element name="tiempoCrec" type="num2"></xs:element>
<xs:element name="beneficio" type="num"></xs:element>


<!-- <coste>0</coste>
        <usos>10</usos>
        <nivel codigo = "n1">Básico</nivel>-->

<xs:element name="herramienta">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="denominacion" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="coste" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="usos" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="nivel" minOccurs="1" maxOccurs="1"></xs:element>
            <xs:element ref="accion" minOccurs="1" maxOccurs="1"></xs:element>
        </xs:sequence>
        <xs:attribute ref="herr"></xs:attribute>
    </xs:complexType>
</xs:element>

<xs:element name="denominacion" type="xs:string"></xs:element>
<xs:element name="coste" type="num"></xs:element>
<xs:element name="usos" type="num2"></xs:element>

<xs:element name="nivel">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="codigo"></xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

<xs:element name="accion" type="xs:string"></xs:element>

<!-- atributos-->
 <xs:attribute name="sem">
    <xs:simpleType>
        <xs:restriction base="xs:ID">
            <xs:pattern value="[a-z]*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:attribute>

<xs:attribute name="herr">
    <xs:simpleType>
        <xs:restriction base="xs:ID">
            <xs:pattern value="[a-z]*[0-9]*"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:attribute>

<xs:attribute name="codigo" type="cod"></xs:attribute>

<!-- tipos de datos-->
<xs:simpleType name="num">
    <xs:restriction base="xs:int">
        <xs:minInclusive value="0"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="num2">
    <xs:restriction base="xs:int">
        <xs:minInclusive value="10"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="cod">
    <xs:restriction base="xs:string">
        <xs:pattern value="n[0-9]+"></xs:pattern>
    </xs:restriction>
</xs:simpleType>


</xs:schema>

=== pmonteroj05/proyecto_granja/datos/tienda.xml
<?xml version="1.0" encoding="UTF-8"?>
<tienda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tienda.xsd">
    
    <!-- semillas-->
    <semilla sem = "cal">
        <nombre>Calabaza</nombre>
        <tipo>Vegetal</tipo>
        <precio>50</precio>
        <tiempoCrec>60</tiempoCrec>
        <beneficio>3</beneficio>
    </semilla>

    <semilla sem = "alc">
        <nombre>Alcachofa</nombre>
        <tipo>Vegetal</tipo>
        <precio>60</precio>
        <tiempoCrec>40</tiempoCrec>
        <beneficio>2</beneficio>
    </semilla>

    <semilla sem = "ber">
        <nombre>Berenjena</nombre>
        <tipo>Vegetal</tipo>
        <precio>70</precio>
        <tiempoCrec>30</tiempoCrec>
        <beneficio>4</beneficio>
    </semilla>

    <semilla sem = "mel">
        <nombre>Melocotón</nombre>
        <tipo>Frutal</tipo>
        <precio>80</precio>
        <tiempoCrec>90</tiempoCrec>
        <beneficio>4</beneficio>
    </semilla>

    <semilla sem = "pla">
        <nombre>Plátano</nombre>
        <tipo>Frutal</tipo>
        <precio>90</precio>
        <tiempoCrec>120</tiempoCrec>
        <beneficio>5</beneficio>
    </semilla>

    <semilla sem = "man">
        <nombre>Manzana</nombre>
        <tipo>Frutal</tipo>
        <precio>100</precio>
        <tiempoCrec>100</tiempoCrec>
        <beneficio>6</beneficio>
    </semilla>

    <semilla sem = "fre">
        <nombre>Fresa</nombre>
        <tipo>Premium</tipo>
        <precio>300</precio>
        <tiempoCrec>10</tiempoCrec>
        <beneficio>7</beneficio>
    </semilla>

    <semilla sem = "pin">
        <nombre>Piña</nombre>
        <tipo>Premium</tipo>
        <precio>300</precio>
        <tiempoCrec>10</tiempoCrec>
        <beneficio>7</beneficio>
    </semilla>

    <!-- herramientas-->
    <herramienta herr = "az1">
        <denominacion>Azada</denominacion>
        <coste>0</coste>
        <usos>10</usos>
        <nivel codigo = "n1">Básico</nivel>
        <accion>sembrar</accion>
    </herramienta>

    <herramienta herr = "reg1">
        <denominacion>Regadera</denominacion>
        <coste>0</coste>
        <usos>10</usos>
        <nivel codigo = "n1">Básico</nivel>
        <accion>regar</accion>
    </herramienta>

    <herramienta herr = "hoz1">
        <denominacion>Hoz</denominacion>
        <coste>0</coste>
        <usos>10</usos>
        <nivel codigo = "n1">Básico</nivel>
        <accion>recoger</accion>
    </herramienta>


        <!-- bronce-->
    <herramienta herr = "az2">
        <denominacion>Azada</denominacion>
        <coste>10</coste>
        <usos>20</usos>
        <nivel codigo = "n2">Bronce</nivel>
        <accion>sembrar</accion>
    </herramienta>

    <herramienta herr = "reg2">
        <denominacion>Regadera</denominacion>
        <coste>10</coste>
        <usos>20</usos>
        <nivel codigo = "n2">Bronce</nivel>
        <accion>regar</accion>
    </herramienta>

    <herramienta herr = "hoz2">
        <denominacion>Hoz</denominacion>
        <coste>10</coste>
        <usos>20</usos>
        <nivel codigo = "n2">Bronce</nivel>
        <accion>recoger</accion>
    </herramienta>

        <!-- Plata-->
    <herramienta herr = "az3">
        <denominacion>Azada</denominacion>
        <coste>50</coste>
        <usos>30</usos>
        <nivel codigo = "n3">Plata</nivel>
        <accion>sembrar</accion>
    </herramienta>

    <herramienta herr = "reg3">
        <denominacion>Regadera</denominacion>
        <coste>50</coste>
        <usos>30</usos>
        <nivel codigo = "n3">Plata</nivel>
        <accion>regar</accion>
    </herramienta>

    <herramienta herr = "hoz3">
        <denominacion>Hoz</denominacion>
        <coste>50</coste>
        <usos>30</usos>
        <nivel codigo = "n3">Plata</nivel>
        <accion>recoger</accion>
    </herramienta>

        <!-- Oro-->
    <herramienta herr = "az4">
        <denominacion>Azada</denominacion>
        <coste>100</coste>
        <usos>40</usos>
        <nivel codigo = "n4">Oro</nivel>
        <accion>sembrar</accion>
    </herramienta>

    <herramienta herr = "reg4">
        <denominacion>Regadera</denominacion>
        <coste>100</coste>
        <usos>40</usos>
        <nivel codigo = "n4">Oro</nivel>
        <accion>regar</accion>
    </herramienta>

    <herramienta herr = "hoz4">
        <denominacion>Hoz</denominacion>
        <coste>100</coste>
        <usos>40</usos>
        <nivel codigo = "n4">Oro</nivel>
        <accion>recoger</accion>
    </herramienta>
</tienda>
